### ISSUE TITLE
Arrow functions for binding "this"

### ISSUE THREAD

**Issue by JasonDGates** [uzumakirfc/uzumaki_project_atelier#8]
https://github.com/uzumakirfc/uzumaki_project_atelier/blob/a9ec8a62e87e597c3a6251c9623bfc0d49e9273d/src/components/reviews/reviewTile.jsx#L15-L18

#### Description
Using arrow functions for our helpers will automatically bind "this" for us, so we can save some time not having to write these bindings.
#### Files
reviewTile.jsx
#### Tasks (optional)
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Refactor revReportHandler into an arrow function.
- [ ] Refactor revHelpfulHandler into an arrow function.
- [ ] Refactor bigImageHandler into an arrow function.
- [ ] Refactor closeImageHandler into an arrow function.
